Repository prefragrance/prefragrance-client, pull requests merged in 2022-10, with the labels that each got.

#21 [Feat] colors.js keyword 색상 추가 / 검색 탭 모달 수정
  src/components/DetailPage/Content/index.js
  src/components/DetailPage/Content/styled.js
  src/components/DetailPage/Tab/index.js
  src/components/DetailPage/Tab/styled.js
  src/components/HomePage/Banner/index.jsx
  src/components/HomePage/Banner/styled.js
  src/components/HomePage/BestReview/index.jsx
  src/components/HomePage/BestReview/styled.js
  src/components/HomePage/Magazine/index.jsx
  src/components/HomePage/Magazine/styled.js
  src/components/HomePage/Recommendation/InfoBox/index.jsx
  src/components/HomePage/Recommendation/InfoBox/styled.js
  src/components/HomePage/Recommendation/index.jsx
  src/components/HomePage/Recommendation/styled.js
  src/components/SearchResultPage/Category/index.js
  src/components/SearchResultPage/Category/styled.js
  src/components/shared/Footer/index.js
  src/components/shared/Footer/styled.js
  src/components/shared/SearchBar/Modal/CategoryModal/CategoryDropdown.jsx
  src/components/shared/SearchBar/Modal/CategoryModal/index.jsx
  src/components/shared/SearchBar/Modal/CategoryModal/style.css
  src/components/shared/SearchBar/Modal/SearchCategoryTab/SearchCategory.jsx
  src/components/shared/SearchBar/Modal/SearchCategoryTab/index.jsx
  src/components/shared/SearchBar/index.jsx
  src/constants/color.js
  src/pages/SearchResultPage.jsx
Labels: UI, refactor

#20 [Refactor] HomePage 리팩토링
  src/components/HomePage/Banner/Banner.jsx
  src/components/HomePage/BestReview/BestReview.jsx
  src/components/HomePage/BestReview/ReviewBox/index.jsx
  src/components/HomePage/BestReview/ReviewBox/styled.js
  src/components/HomePage/BestReview/index.js
  src/components/HomePage/Magazine/Magazine.jsx
  src/components/HomePage/Magazine/MagazineBox/index.jsx
  src/components/HomePage/Magazine/MagazineBox/styled.js
  src/components/shared/component/SearchBar/index.jsx
  src/components/shared/component/SearchBar/styled.js
  src/components/shared/page/Footer/styled.js
  src/components/shared/page/MainContainer/styled.js
  src/components/shared/page/Nav/index.js
  src/components/shared/page/Nav/styled.js
Labels: UI, API

#22 [Fix] 간단한 리팩토링, 검색 카테고리 드롭다운 ref 설정
  src/App.js
  src/components/shared/Footer/index.js
  src/components/shared/Footer/styled.js
  src/components/shared/SearchBar/Modal/CategoryModal/CategoryDropdown.jsx
  src/components/shared/SearchBar/Modal/CategoryModal/style.css
  src/components/shared/SearchBar/Modal/SearchCategoryTab/SearchCategory.jsx
  src/components/shared/SearchBar/Modal/SearchCategoryTab/index.jsx
  src/components/shared/SearchBar/SearchCategoryDropdown/index.jsx
  src/components/shared/SearchBar/SearchModal/KeywordList/index.jsx
  src/components/shared/SearchBar/index.jsx
  src/components/shared/component/SearchBar/index.jsx
  src/components/shared/component/SearchBar/styled.js
  src/components/shared/layout/Footer/index.jsx
  src/components/shared/layout/Nav/index.jsx
  src/components/shared/page/Footer/styled.js
  src/components/shared/page/MainContainer/styled.js
  src/components/shared/page/Nav/index.js
  src/components/shared/page/Nav/styled.js
Labels: enhancement

#18 [Feat] 검색결과 페이지 UI
  package-lock.json
  src/App.js
  src/components/SearchResultPage/SearchResultList/SearchResultBlock.jsx
  src/components/SearchResultPage/SearchResultList/index.jsx
  src/components/shared/SearchBar/index.jsx
  src/hook/useClickOutside.js
  src/pages/SearchResultPage.jsx
  yarn.lock
Labels: UI
